version: "3.9"
services:
  postgresql:
    image: postgres:16-alpine
    env_file: db.env
    volumes:
      - dbdata:/var/lib/postgresql/data/
      - ./conf/pg_hba.conf:/var/lib/postgresql/data/pg_hba.conf
      - ./conf/postgresql.conf:/var/lib/postgresql/data/postgresql.conf
      - ./certs:/var/lib/postgresql/data/ssl
    restart: unless-stopped
    ports:
      - 5432:5432 # comment this if you wish to use pgbouncer

  # pgbouncer:
  #   image: bitnami/pgbouncer:1.22.0
  #   env_file: pgbouncer.env
  #   ports:
  #     - 6432:6432
  #   depends_on:
  #     - postgresql
  #   volumes:
  #     - ./certs:/var/lib/postgresql/data/ssl
  #     - ./conf/userlists/txt:/etc/pgbouncer/userlists.txt
  #     - ./conf:/bitnami/pgbouncer/conf/

  backup:
    build: .
    env_file: app.env
    restart: unless-stopped
    tmpfs:
      - /tmpß

volumes:
  dbdata:
    driver: local
